using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoRoute.Engine;
using AutoRoute.Engine.Model;

namespace AutoRoute.Tests;

public sealed class SinkDropInWriterTests : IDisposable
{
    private readonly string _dir;
    private readonly string _path;

    public SinkDropInWriterTests()
    {
        _dir = Path.Combine(Path.GetTempPath(), "autoroute-tests", Guid.NewGuid().ToString("N"));
        _path = Path.Combine(_dir, "pipewire-pulse.conf.d", SinkDropInWriter.FileName);
    }

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); } catch { /* best-effort */ }
    }

    private static VirtualSinkSpec Sink(string name, string? description = null, SinkChannels channels = SinkChannels.Stereo)
        => new(Guid.NewGuid().ToString("N"), name, description ?? name, channels);

    [Fact]
    public void Generate_golden_output_is_stable_and_escaped()
    {
        // Declared out of order — output must sort by name.
        var text = SinkDropInWriter.Generate(new[]
        {
            Sink("MusicSink", "Music Sink"),
            Sink("GameSink", "Game Sink"),
            Sink("Narration", "Narration", SinkChannels.Mono),
        });

        const string expected =
            "# Generated by AutoRoute — DO NOT EDIT (edits will be overwritten).\n" +
            "# Declared sinks live in ~/.config/autoroute/rules.json (\"virtualSinks\").\n" +
            "pulse.cmd = [\n" +
            "    { cmd = \"load-module\" args = \"module-null-sink sink_name=GameSink sink_properties=\\\"device.description='Game Sink' autoroute.managed=true\\\"\" flags = [ ] }\n" +
            "    { cmd = \"load-module\" args = \"module-null-sink sink_name=MusicSink sink_properties=\\\"device.description='Music Sink' autoroute.managed=true\\\"\" flags = [ ] }\n" +
            "    { cmd = \"load-module\" args = \"module-null-sink sink_name=Narration channels=1 channel_map=mono sink_properties=\\\"device.description='Narration' autoroute.managed=true\\\"\" flags = [ ] }\n" +
            "]\n";
        Assert.Equal(expected, text);
    }

    [Fact]
    public async Task SyncAsync_creates_directory_and_writes_atomically()
    {
        var writer = new SinkDropInWriter(_path);
        await writer.SyncAsync(new[] { Sink("GameSink") });

        Assert.True(File.Exists(_path));
        Assert.Contains("sink_name=GameSink", await File.ReadAllTextAsync(_path));
        // No leftover temp siblings.
        Assert.Equal(new[] { SinkDropInWriter.FileName },
            Directory.GetFiles(Path.GetDirectoryName(_path)!).Select(Path.GetFileName).ToArray());
    }

    [Fact]
    public async Task SyncAsync_is_write_if_changed()
    {
        var writer = new SinkDropInWriter(_path);
        var sinks = new[] { Sink("GameSink") };
        await writer.SyncAsync(sinks);

        var firstWrite = File.GetLastWriteTimeUtc(_path);
        await Task.Delay(50);
        await writer.SyncAsync(sinks); // identical content → no-op

        Assert.Equal(firstWrite, File.GetLastWriteTimeUtc(_path)); // mtime untouched
    }

    [Fact]
    public async Task SyncAsync_empty_set_deletes_the_file()
    {
        var writer = new SinkDropInWriter(_path);
        await writer.SyncAsync(new[] { Sink("GameSink") });
        Assert.True(File.Exists(_path));

        await writer.SyncAsync(Array.Empty<VirtualSinkSpec>());
        Assert.False(File.Exists(_path));

        // And an already-absent file is a clean no-op.
        await writer.SyncAsync(Array.Empty<VirtualSinkSpec>());
        Assert.False(File.Exists(_path));
    }
}
