using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using AutoRoute.Engine.Model;
using AutoRoute.PipeWire;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace AutoRoute.Engine;

/// <summary>
/// Generates and maintains the pipewire-pulse conf.d drop-in that recreates the declared virtual
/// sinks at boot (ADR-0011 hybrid mechanism: the drop-in gives persistence without AutoRoute
/// running; instant effect always comes from pactl). The file is fully owned by AutoRoute —
/// regenerated from the declared set on every reconcile pass, written only when the content
/// actually changed, atomically. An empty declared set deletes the file rather than leaving a
/// stale one behind.
/// </summary>
public sealed class SinkDropInWriter
{
    public const string FileName = "autoroute-sinks.conf";

    private const string Header =
        "# Generated by AutoRoute — DO NOT EDIT (edits will be overwritten).\n" +
        "# Declared sinks live in ~/.config/autoroute/rules.json (\"virtualSinks\").\n";

    private readonly string _path;
    private readonly ILogger _log;

    public SinkDropInWriter(string path, ILogger<SinkDropInWriter>? log = null)
    {
        _path = Path.GetFullPath(path);
        _log = log ?? NullLogger<SinkDropInWriter>.Instance;
    }

    /// <summary><c>$XDG_CONFIG_HOME/pipewire/pipewire-pulse.conf.d/autoroute-sinks.conf</c>.</summary>
    public static string DefaultPath()
    {
        var configHome = Environment.GetEnvironmentVariable("XDG_CONFIG_HOME");
        if (string.IsNullOrWhiteSpace(configHome))
        {
            var home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
            configHome = Path.Combine(home, ".config");
        }
        return Path.Combine(configHome, "pipewire", "pipewire-pulse.conf.d", FileName);
    }

    /// <summary>
    /// Pure content generation (golden-testable). Each entry's module args are built by
    /// <see cref="PactlSinkController.BuildModuleArgs"/> — the very tokens the runtime pactl call
    /// uses — so boot-created and runtime-created sinks are byte-identical. Entries are ordered by
    /// name so the output is stable regardless of declaration order.
    /// </summary>
    public static string Generate(IReadOnlyList<VirtualSinkSpec> sinks)
    {
        var sb = new StringBuilder(Header);
        sb.Append("pulse.cmd = [\n");
        foreach (var sink in sinks.OrderBy(s => s.Name, StringComparer.Ordinal))
        {
            var moduleArgs = PactlSinkController.BuildModuleArgs(
                new NullSinkRequest(sink.Name, sink.Description, sink.Channels == SinkChannels.Mono));
            // SPA-JSON: the args value is double-quoted, so literal double quotes inside the
            // module args (around sink_properties) are backslash-escaped.
            var args = ("module-null-sink " + string.Join(' ', moduleArgs)).Replace("\"", "\\\"");
            sb.Append("    { cmd = \"load-module\" args = \"").Append(args).Append("\" flags = [ ] }\n");
        }
        sb.Append("]\n");
        return sb.ToString();
    }

    /// <summary>Converges the on-disk drop-in to the declared set. Write-if-changed, atomic.</summary>
    public async Task SyncAsync(IReadOnlyList<VirtualSinkSpec> sinks, CancellationToken ct = default)
    {
        if (sinks.Count == 0)
        {
            if (File.Exists(_path))
            {
                File.Delete(_path);
                _log.LogInformation("no declared sinks; removed {Path}", _path);
            }
            return;
        }

        var text = Generate(sinks);
        if (File.Exists(_path) && await File.ReadAllTextAsync(_path, ct).ConfigureAwait(false) == text)
            return; // already converged — don't churn mtime

        var dir = Path.GetDirectoryName(_path)!;
        Directory.CreateDirectory(dir);
        await AtomicFile.WriteAsync(_path, text, UnixFileMode.UserRead | UnixFileMode.UserWrite, ct)
            .ConfigureAwait(false);
        _log.LogInformation("synced {Count} declared sink(s) to {Path}", sinks.Count, _path);
    }
}
